/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDossiersRouteImport } from './routes/_authenticated/dossiers'
import { Route as AuthenticatedDossiersIdRouteImport } from './routes/_authenticated/dossiers.$id'
import { Route as AuthenticatedDossiersIdIndexRouteImport } from './routes/_authenticated/dossiers.$id.index'
import { Route as AuthenticatedDossiersIdSurvieProchesRouteImport } from './routes/_authenticated/dossiers.$id.survie-proches'
import { Route as AuthenticatedDossiersIdPatrimoniauxTemporairesRouteImport } from './routes/_authenticated/dossiers.$id.patrimoniaux-temporaires'
import { Route as AuthenticatedDossiersIdPatrimoniauxPermanentsRouteImport } from './routes/_authenticated/dossiers.$id.patrimoniaux-permanents'
import { Route as AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRouteImport } from './routes/_authenticated/dossiers.$id.extrapatrimoniaux-temporaires'
import { Route as AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRouteImport } from './routes/_authenticated/dossiers.$id.extrapatrimoniaux-permanents'
import { Route as AuthenticatedDossiersIdDecesRouteImport } from './routes/_authenticated/dossiers.$id.deces'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDossiersRoute = AuthenticatedDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDossiersIdRoute = AuthenticatedDossiersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDossiersRoute,
} as any)
const AuthenticatedDossiersIdIndexRoute =
  AuthenticatedDossiersIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdSurvieProchesRoute =
  AuthenticatedDossiersIdSurvieProchesRouteImport.update({
    id: '/survie-proches',
    path: '/survie-proches',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdPatrimoniauxTemporairesRoute =
  AuthenticatedDossiersIdPatrimoniauxTemporairesRouteImport.update({
    id: '/patrimoniaux-temporaires',
    path: '/patrimoniaux-temporaires',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdPatrimoniauxPermanentsRoute =
  AuthenticatedDossiersIdPatrimoniauxPermanentsRouteImport.update({
    id: '/patrimoniaux-permanents',
    path: '/patrimoniaux-permanents',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRoute =
  AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRouteImport.update({
    id: '/extrapatrimoniaux-temporaires',
    path: '/extrapatrimoniaux-temporaires',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRoute =
  AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRouteImport.update({
    id: '/extrapatrimoniaux-permanents',
    path: '/extrapatrimoniaux-permanents',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdDecesRoute =
  AuthenticatedDossiersIdDecesRouteImport.update({
    id: '/deces',
    path: '/deces',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dossiers': typeof AuthenticatedDossiersRouteWithChildren
  '/dossiers/$id': typeof AuthenticatedDossiersIdRouteWithChildren
  '/dossiers/$id/deces': typeof AuthenticatedDossiersIdDecesRoute
  '/dossiers/$id/extrapatrimoniaux-permanents': typeof AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRoute
  '/dossiers/$id/extrapatrimoniaux-temporaires': typeof AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRoute
  '/dossiers/$id/patrimoniaux-permanents': typeof AuthenticatedDossiersIdPatrimoniauxPermanentsRoute
  '/dossiers/$id/patrimoniaux-temporaires': typeof AuthenticatedDossiersIdPatrimoniauxTemporairesRoute
  '/dossiers/$id/survie-proches': typeof AuthenticatedDossiersIdSurvieProchesRoute
  '/dossiers/$id/': typeof AuthenticatedDossiersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dossiers': typeof AuthenticatedDossiersRouteWithChildren
  '/dossiers/$id/deces': typeof AuthenticatedDossiersIdDecesRoute
  '/dossiers/$id/extrapatrimoniaux-permanents': typeof AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRoute
  '/dossiers/$id/extrapatrimoniaux-temporaires': typeof AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRoute
  '/dossiers/$id/patrimoniaux-permanents': typeof AuthenticatedDossiersIdPatrimoniauxPermanentsRoute
  '/dossiers/$id/patrimoniaux-temporaires': typeof AuthenticatedDossiersIdPatrimoniauxTemporairesRoute
  '/dossiers/$id/survie-proches': typeof AuthenticatedDossiersIdSurvieProchesRoute
  '/dossiers/$id': typeof AuthenticatedDossiersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dossiers': typeof AuthenticatedDossiersRouteWithChildren
  '/_authenticated/dossiers/$id': typeof AuthenticatedDossiersIdRouteWithChildren
  '/_authenticated/dossiers/$id/deces': typeof AuthenticatedDossiersIdDecesRoute
  '/_authenticated/dossiers/$id/extrapatrimoniaux-permanents': typeof AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRoute
  '/_authenticated/dossiers/$id/extrapatrimoniaux-temporaires': typeof AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRoute
  '/_authenticated/dossiers/$id/patrimoniaux-permanents': typeof AuthenticatedDossiersIdPatrimoniauxPermanentsRoute
  '/_authenticated/dossiers/$id/patrimoniaux-temporaires': typeof AuthenticatedDossiersIdPatrimoniauxTemporairesRoute
  '/_authenticated/dossiers/$id/survie-proches': typeof AuthenticatedDossiersIdSurvieProchesRoute
  '/_authenticated/dossiers/$id/': typeof AuthenticatedDossiersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dossiers'
    | '/dossiers/$id'
    | '/dossiers/$id/deces'
    | '/dossiers/$id/extrapatrimoniaux-permanents'
    | '/dossiers/$id/extrapatrimoniaux-temporaires'
    | '/dossiers/$id/patrimoniaux-permanents'
    | '/dossiers/$id/patrimoniaux-temporaires'
    | '/dossiers/$id/survie-proches'
    | '/dossiers/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dossiers'
    | '/dossiers/$id/deces'
    | '/dossiers/$id/extrapatrimoniaux-permanents'
    | '/dossiers/$id/extrapatrimoniaux-temporaires'
    | '/dossiers/$id/patrimoniaux-permanents'
    | '/dossiers/$id/patrimoniaux-temporaires'
    | '/dossiers/$id/survie-proches'
    | '/dossiers/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dossiers'
    | '/_authenticated/dossiers/$id'
    | '/_authenticated/dossiers/$id/deces'
    | '/_authenticated/dossiers/$id/extrapatrimoniaux-permanents'
    | '/_authenticated/dossiers/$id/extrapatrimoniaux-temporaires'
    | '/_authenticated/dossiers/$id/patrimoniaux-permanents'
    | '/_authenticated/dossiers/$id/patrimoniaux-temporaires'
    | '/_authenticated/dossiers/$id/survie-proches'
    | '/_authenticated/dossiers/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dossiers': {
      id: '/_authenticated/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof AuthenticatedDossiersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dossiers/$id': {
      id: '/_authenticated/dossiers/$id'
      path: '/$id'
      fullPath: '/dossiers/$id'
      preLoaderRoute: typeof AuthenticatedDossiersIdRouteImport
      parentRoute: typeof AuthenticatedDossiersRoute
    }
    '/_authenticated/dossiers/$id/': {
      id: '/_authenticated/dossiers/$id/'
      path: '/'
      fullPath: '/dossiers/$id/'
      preLoaderRoute: typeof AuthenticatedDossiersIdIndexRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/survie-proches': {
      id: '/_authenticated/dossiers/$id/survie-proches'
      path: '/survie-proches'
      fullPath: '/dossiers/$id/survie-proches'
      preLoaderRoute: typeof AuthenticatedDossiersIdSurvieProchesRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/patrimoniaux-temporaires': {
      id: '/_authenticated/dossiers/$id/patrimoniaux-temporaires'
      path: '/patrimoniaux-temporaires'
      fullPath: '/dossiers/$id/patrimoniaux-temporaires'
      preLoaderRoute: typeof AuthenticatedDossiersIdPatrimoniauxTemporairesRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/patrimoniaux-permanents': {
      id: '/_authenticated/dossiers/$id/patrimoniaux-permanents'
      path: '/patrimoniaux-permanents'
      fullPath: '/dossiers/$id/patrimoniaux-permanents'
      preLoaderRoute: typeof AuthenticatedDossiersIdPatrimoniauxPermanentsRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/extrapatrimoniaux-temporaires': {
      id: '/_authenticated/dossiers/$id/extrapatrimoniaux-temporaires'
      path: '/extrapatrimoniaux-temporaires'
      fullPath: '/dossiers/$id/extrapatrimoniaux-temporaires'
      preLoaderRoute: typeof AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/extrapatrimoniaux-permanents': {
      id: '/_authenticated/dossiers/$id/extrapatrimoniaux-permanents'
      path: '/extrapatrimoniaux-permanents'
      fullPath: '/dossiers/$id/extrapatrimoniaux-permanents'
      preLoaderRoute: typeof AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/deces': {
      id: '/_authenticated/dossiers/$id/deces'
      path: '/deces'
      fullPath: '/dossiers/$id/deces'
      preLoaderRoute: typeof AuthenticatedDossiersIdDecesRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
  }
}

interface AuthenticatedDossiersIdRouteChildren {
  AuthenticatedDossiersIdDecesRoute: typeof AuthenticatedDossiersIdDecesRoute
  AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRoute: typeof AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRoute
  AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRoute: typeof AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRoute
  AuthenticatedDossiersIdPatrimoniauxPermanentsRoute: typeof AuthenticatedDossiersIdPatrimoniauxPermanentsRoute
  AuthenticatedDossiersIdPatrimoniauxTemporairesRoute: typeof AuthenticatedDossiersIdPatrimoniauxTemporairesRoute
  AuthenticatedDossiersIdSurvieProchesRoute: typeof AuthenticatedDossiersIdSurvieProchesRoute
  AuthenticatedDossiersIdIndexRoute: typeof AuthenticatedDossiersIdIndexRoute
}

const AuthenticatedDossiersIdRouteChildren: AuthenticatedDossiersIdRouteChildren =
  {
    AuthenticatedDossiersIdDecesRoute: AuthenticatedDossiersIdDecesRoute,
    AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRoute:
      AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRoute,
    AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRoute:
      AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRoute,
    AuthenticatedDossiersIdPatrimoniauxPermanentsRoute:
      AuthenticatedDossiersIdPatrimoniauxPermanentsRoute,
    AuthenticatedDossiersIdPatrimoniauxTemporairesRoute:
      AuthenticatedDossiersIdPatrimoniauxTemporairesRoute,
    AuthenticatedDossiersIdSurvieProchesRoute:
      AuthenticatedDossiersIdSurvieProchesRoute,
    AuthenticatedDossiersIdIndexRoute: AuthenticatedDossiersIdIndexRoute,
  }

const AuthenticatedDossiersIdRouteWithChildren =
  AuthenticatedDossiersIdRoute._addFileChildren(
    AuthenticatedDossiersIdRouteChildren,
  )

interface AuthenticatedDossiersRouteChildren {
  AuthenticatedDossiersIdRoute: typeof AuthenticatedDossiersIdRouteWithChildren
}

const AuthenticatedDossiersRouteChildren: AuthenticatedDossiersRouteChildren = {
  AuthenticatedDossiersIdRoute: AuthenticatedDossiersIdRouteWithChildren,
}

const AuthenticatedDossiersRouteWithChildren =
  AuthenticatedDossiersRoute._addFileChildren(
    AuthenticatedDossiersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDossiersRoute: typeof AuthenticatedDossiersRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDossiersRoute: AuthenticatedDossiersRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
