/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTauxLegalRouteImport } from './routes/_authenticated/taux-legal'
import { Route as AuthenticatedReferentielsRouteImport } from './routes/_authenticated/referentiels'
import { Route as AuthenticatedCabinetRouteImport } from './routes/_authenticated/cabinet'
import { Route as AuthenticatedReferentielsIndexRouteImport } from './routes/_authenticated/referentiels.index'
import { Route as AuthenticatedDossiersIndexRouteImport } from './routes/_authenticated/dossiers.index'
import { Route as AuthenticatedReferentielsCodeRouteImport } from './routes/_authenticated/referentiels.$code'
import { Route as AuthenticatedDossiersIdRouteImport } from './routes/_authenticated/dossiers.$id'
import { Route as AuthenticatedDossiersIdIndexRouteImport } from './routes/_authenticated/dossiers.$id.index'
import { Route as AuthenticatedDossiersIdTiersPayeursRouteImport } from './routes/_authenticated/dossiers.$id.tiers-payeurs'
import { Route as AuthenticatedDossiersIdSyntheseRouteImport } from './routes/_authenticated/dossiers.$id.synthese'
import { Route as AuthenticatedDossiersIdSurvieProchesRouteImport } from './routes/_authenticated/dossiers.$id.survie-proches'
import { Route as AuthenticatedDossiersIdPatrimoniauxTemporairesRouteImport } from './routes/_authenticated/dossiers.$id.patrimoniaux-temporaires'
import { Route as AuthenticatedDossiersIdPatrimoniauxPermanentsRouteImport } from './routes/_authenticated/dossiers.$id.patrimoniaux-permanents'
import { Route as AuthenticatedDossiersIdInteretsRouteImport } from './routes/_authenticated/dossiers.$id.interets'
import { Route as AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRouteImport } from './routes/_authenticated/dossiers.$id.extrapatrimoniaux-temporaires'
import { Route as AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRouteImport } from './routes/_authenticated/dossiers.$id.extrapatrimoniaux-permanents'
import { Route as AuthenticatedDossiersIdDecesRouteImport } from './routes/_authenticated/dossiers.$id.deces'
import { Route as AuthenticatedDossiersIdComparateurRouteImport } from './routes/_authenticated/dossiers.$id.comparateur'
import { Route as AuthenticatedDossiersIdActiviteRouteImport } from './routes/_authenticated/dossiers.$id.activite'
import { Route as AuthenticatedReferentielsCodeEditionsEditionIdRouteImport } from './routes/_authenticated/referentiels.$code.editions.$editionId'
import { Route as AuthenticatedDossiersIdSnapshotsSnapshotIdRouteImport } from './routes/_authenticated/dossiers.$id.snapshots.$snapshotId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTauxLegalRoute = AuthenticatedTauxLegalRouteImport.update({
  id: '/taux-legal',
  path: '/taux-legal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferentielsRoute =
  AuthenticatedReferentielsRouteImport.update({
    id: '/referentiels',
    path: '/referentiels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCabinetRoute = AuthenticatedCabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferentielsIndexRoute =
  AuthenticatedReferentielsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReferentielsRoute,
  } as any)
const AuthenticatedDossiersIndexRoute =
  AuthenticatedDossiersIndexRouteImport.update({
    id: '/dossiers/',
    path: '/dossiers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReferentielsCodeRoute =
  AuthenticatedReferentielsCodeRouteImport.update({
    id: '/$code',
    path: '/$code',
    getParentRoute: () => AuthenticatedReferentielsRoute,
  } as any)
const AuthenticatedDossiersIdRoute = AuthenticatedDossiersIdRouteImport.update({
  id: '/dossiers/$id',
  path: '/dossiers/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDossiersIdIndexRoute =
  AuthenticatedDossiersIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdTiersPayeursRoute =
  AuthenticatedDossiersIdTiersPayeursRouteImport.update({
    id: '/tiers-payeurs',
    path: '/tiers-payeurs',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdSyntheseRoute =
  AuthenticatedDossiersIdSyntheseRouteImport.update({
    id: '/synthese',
    path: '/synthese',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdSurvieProchesRoute =
  AuthenticatedDossiersIdSurvieProchesRouteImport.update({
    id: '/survie-proches',
    path: '/survie-proches',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdPatrimoniauxTemporairesRoute =
  AuthenticatedDossiersIdPatrimoniauxTemporairesRouteImport.update({
    id: '/patrimoniaux-temporaires',
    path: '/patrimoniaux-temporaires',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdPatrimoniauxPermanentsRoute =
  AuthenticatedDossiersIdPatrimoniauxPermanentsRouteImport.update({
    id: '/patrimoniaux-permanents',
    path: '/patrimoniaux-permanents',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdInteretsRoute =
  AuthenticatedDossiersIdInteretsRouteImport.update({
    id: '/interets',
    path: '/interets',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRoute =
  AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRouteImport.update({
    id: '/extrapatrimoniaux-temporaires',
    path: '/extrapatrimoniaux-temporaires',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRoute =
  AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRouteImport.update({
    id: '/extrapatrimoniaux-permanents',
    path: '/extrapatrimoniaux-permanents',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdDecesRoute =
  AuthenticatedDossiersIdDecesRouteImport.update({
    id: '/deces',
    path: '/deces',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdComparateurRoute =
  AuthenticatedDossiersIdComparateurRouteImport.update({
    id: '/comparateur',
    path: '/comparateur',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedDossiersIdActiviteRoute =
  AuthenticatedDossiersIdActiviteRouteImport.update({
    id: '/activite',
    path: '/activite',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)
const AuthenticatedReferentielsCodeEditionsEditionIdRoute =
  AuthenticatedReferentielsCodeEditionsEditionIdRouteImport.update({
    id: '/editions/$editionId',
    path: '/editions/$editionId',
    getParentRoute: () => AuthenticatedReferentielsCodeRoute,
  } as any)
const AuthenticatedDossiersIdSnapshotsSnapshotIdRoute =
  AuthenticatedDossiersIdSnapshotsSnapshotIdRouteImport.update({
    id: '/snapshots/$snapshotId',
    path: '/snapshots/$snapshotId',
    getParentRoute: () => AuthenticatedDossiersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cabinet': typeof AuthenticatedCabinetRoute
  '/referentiels': typeof AuthenticatedReferentielsRouteWithChildren
  '/taux-legal': typeof AuthenticatedTauxLegalRoute
  '/dossiers/$id': typeof AuthenticatedDossiersIdRouteWithChildren
  '/referentiels/$code': typeof AuthenticatedReferentielsCodeRouteWithChildren
  '/dossiers/': typeof AuthenticatedDossiersIndexRoute
  '/referentiels/': typeof AuthenticatedReferentielsIndexRoute
  '/dossiers/$id/activite': typeof AuthenticatedDossiersIdActiviteRoute
  '/dossiers/$id/comparateur': typeof AuthenticatedDossiersIdComparateurRoute
  '/dossiers/$id/deces': typeof AuthenticatedDossiersIdDecesRoute
  '/dossiers/$id/extrapatrimoniaux-permanents': typeof AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRoute
  '/dossiers/$id/extrapatrimoniaux-temporaires': typeof AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRoute
  '/dossiers/$id/interets': typeof AuthenticatedDossiersIdInteretsRoute
  '/dossiers/$id/patrimoniaux-permanents': typeof AuthenticatedDossiersIdPatrimoniauxPermanentsRoute
  '/dossiers/$id/patrimoniaux-temporaires': typeof AuthenticatedDossiersIdPatrimoniauxTemporairesRoute
  '/dossiers/$id/survie-proches': typeof AuthenticatedDossiersIdSurvieProchesRoute
  '/dossiers/$id/synthese': typeof AuthenticatedDossiersIdSyntheseRoute
  '/dossiers/$id/tiers-payeurs': typeof AuthenticatedDossiersIdTiersPayeursRoute
  '/dossiers/$id/': typeof AuthenticatedDossiersIdIndexRoute
  '/dossiers/$id/snapshots/$snapshotId': typeof AuthenticatedDossiersIdSnapshotsSnapshotIdRoute
  '/referentiels/$code/editions/$editionId': typeof AuthenticatedReferentielsCodeEditionsEditionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cabinet': typeof AuthenticatedCabinetRoute
  '/taux-legal': typeof AuthenticatedTauxLegalRoute
  '/referentiels/$code': typeof AuthenticatedReferentielsCodeRouteWithChildren
  '/dossiers': typeof AuthenticatedDossiersIndexRoute
  '/referentiels': typeof AuthenticatedReferentielsIndexRoute
  '/dossiers/$id/activite': typeof AuthenticatedDossiersIdActiviteRoute
  '/dossiers/$id/comparateur': typeof AuthenticatedDossiersIdComparateurRoute
  '/dossiers/$id/deces': typeof AuthenticatedDossiersIdDecesRoute
  '/dossiers/$id/extrapatrimoniaux-permanents': typeof AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRoute
  '/dossiers/$id/extrapatrimoniaux-temporaires': typeof AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRoute
  '/dossiers/$id/interets': typeof AuthenticatedDossiersIdInteretsRoute
  '/dossiers/$id/patrimoniaux-permanents': typeof AuthenticatedDossiersIdPatrimoniauxPermanentsRoute
  '/dossiers/$id/patrimoniaux-temporaires': typeof AuthenticatedDossiersIdPatrimoniauxTemporairesRoute
  '/dossiers/$id/survie-proches': typeof AuthenticatedDossiersIdSurvieProchesRoute
  '/dossiers/$id/synthese': typeof AuthenticatedDossiersIdSyntheseRoute
  '/dossiers/$id/tiers-payeurs': typeof AuthenticatedDossiersIdTiersPayeursRoute
  '/dossiers/$id': typeof AuthenticatedDossiersIdIndexRoute
  '/dossiers/$id/snapshots/$snapshotId': typeof AuthenticatedDossiersIdSnapshotsSnapshotIdRoute
  '/referentiels/$code/editions/$editionId': typeof AuthenticatedReferentielsCodeEditionsEditionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/cabinet': typeof AuthenticatedCabinetRoute
  '/_authenticated/referentiels': typeof AuthenticatedReferentielsRouteWithChildren
  '/_authenticated/taux-legal': typeof AuthenticatedTauxLegalRoute
  '/_authenticated/dossiers/$id': typeof AuthenticatedDossiersIdRouteWithChildren
  '/_authenticated/referentiels/$code': typeof AuthenticatedReferentielsCodeRouteWithChildren
  '/_authenticated/dossiers/': typeof AuthenticatedDossiersIndexRoute
  '/_authenticated/referentiels/': typeof AuthenticatedReferentielsIndexRoute
  '/_authenticated/dossiers/$id/activite': typeof AuthenticatedDossiersIdActiviteRoute
  '/_authenticated/dossiers/$id/comparateur': typeof AuthenticatedDossiersIdComparateurRoute
  '/_authenticated/dossiers/$id/deces': typeof AuthenticatedDossiersIdDecesRoute
  '/_authenticated/dossiers/$id/extrapatrimoniaux-permanents': typeof AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRoute
  '/_authenticated/dossiers/$id/extrapatrimoniaux-temporaires': typeof AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRoute
  '/_authenticated/dossiers/$id/interets': typeof AuthenticatedDossiersIdInteretsRoute
  '/_authenticated/dossiers/$id/patrimoniaux-permanents': typeof AuthenticatedDossiersIdPatrimoniauxPermanentsRoute
  '/_authenticated/dossiers/$id/patrimoniaux-temporaires': typeof AuthenticatedDossiersIdPatrimoniauxTemporairesRoute
  '/_authenticated/dossiers/$id/survie-proches': typeof AuthenticatedDossiersIdSurvieProchesRoute
  '/_authenticated/dossiers/$id/synthese': typeof AuthenticatedDossiersIdSyntheseRoute
  '/_authenticated/dossiers/$id/tiers-payeurs': typeof AuthenticatedDossiersIdTiersPayeursRoute
  '/_authenticated/dossiers/$id/': typeof AuthenticatedDossiersIdIndexRoute
  '/_authenticated/dossiers/$id/snapshots/$snapshotId': typeof AuthenticatedDossiersIdSnapshotsSnapshotIdRoute
  '/_authenticated/referentiels/$code/editions/$editionId': typeof AuthenticatedReferentielsCodeEditionsEditionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/cabinet'
    | '/referentiels'
    | '/taux-legal'
    | '/dossiers/$id'
    | '/referentiels/$code'
    | '/dossiers/'
    | '/referentiels/'
    | '/dossiers/$id/activite'
    | '/dossiers/$id/comparateur'
    | '/dossiers/$id/deces'
    | '/dossiers/$id/extrapatrimoniaux-permanents'
    | '/dossiers/$id/extrapatrimoniaux-temporaires'
    | '/dossiers/$id/interets'
    | '/dossiers/$id/patrimoniaux-permanents'
    | '/dossiers/$id/patrimoniaux-temporaires'
    | '/dossiers/$id/survie-proches'
    | '/dossiers/$id/synthese'
    | '/dossiers/$id/tiers-payeurs'
    | '/dossiers/$id/'
    | '/dossiers/$id/snapshots/$snapshotId'
    | '/referentiels/$code/editions/$editionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/cabinet'
    | '/taux-legal'
    | '/referentiels/$code'
    | '/dossiers'
    | '/referentiels'
    | '/dossiers/$id/activite'
    | '/dossiers/$id/comparateur'
    | '/dossiers/$id/deces'
    | '/dossiers/$id/extrapatrimoniaux-permanents'
    | '/dossiers/$id/extrapatrimoniaux-temporaires'
    | '/dossiers/$id/interets'
    | '/dossiers/$id/patrimoniaux-permanents'
    | '/dossiers/$id/patrimoniaux-temporaires'
    | '/dossiers/$id/survie-proches'
    | '/dossiers/$id/synthese'
    | '/dossiers/$id/tiers-payeurs'
    | '/dossiers/$id'
    | '/dossiers/$id/snapshots/$snapshotId'
    | '/referentiels/$code/editions/$editionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/cabinet'
    | '/_authenticated/referentiels'
    | '/_authenticated/taux-legal'
    | '/_authenticated/dossiers/$id'
    | '/_authenticated/referentiels/$code'
    | '/_authenticated/dossiers/'
    | '/_authenticated/referentiels/'
    | '/_authenticated/dossiers/$id/activite'
    | '/_authenticated/dossiers/$id/comparateur'
    | '/_authenticated/dossiers/$id/deces'
    | '/_authenticated/dossiers/$id/extrapatrimoniaux-permanents'
    | '/_authenticated/dossiers/$id/extrapatrimoniaux-temporaires'
    | '/_authenticated/dossiers/$id/interets'
    | '/_authenticated/dossiers/$id/patrimoniaux-permanents'
    | '/_authenticated/dossiers/$id/patrimoniaux-temporaires'
    | '/_authenticated/dossiers/$id/survie-proches'
    | '/_authenticated/dossiers/$id/synthese'
    | '/_authenticated/dossiers/$id/tiers-payeurs'
    | '/_authenticated/dossiers/$id/'
    | '/_authenticated/dossiers/$id/snapshots/$snapshotId'
    | '/_authenticated/referentiels/$code/editions/$editionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/taux-legal': {
      id: '/_authenticated/taux-legal'
      path: '/taux-legal'
      fullPath: '/taux-legal'
      preLoaderRoute: typeof AuthenticatedTauxLegalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referentiels': {
      id: '/_authenticated/referentiels'
      path: '/referentiels'
      fullPath: '/referentiels'
      preLoaderRoute: typeof AuthenticatedReferentielsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet': {
      id: '/_authenticated/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof AuthenticatedCabinetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referentiels/': {
      id: '/_authenticated/referentiels/'
      path: '/'
      fullPath: '/referentiels/'
      preLoaderRoute: typeof AuthenticatedReferentielsIndexRouteImport
      parentRoute: typeof AuthenticatedReferentielsRoute
    }
    '/_authenticated/dossiers/': {
      id: '/_authenticated/dossiers/'
      path: '/dossiers'
      fullPath: '/dossiers/'
      preLoaderRoute: typeof AuthenticatedDossiersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referentiels/$code': {
      id: '/_authenticated/referentiels/$code'
      path: '/$code'
      fullPath: '/referentiels/$code'
      preLoaderRoute: typeof AuthenticatedReferentielsCodeRouteImport
      parentRoute: typeof AuthenticatedReferentielsRoute
    }
    '/_authenticated/dossiers/$id': {
      id: '/_authenticated/dossiers/$id'
      path: '/dossiers/$id'
      fullPath: '/dossiers/$id'
      preLoaderRoute: typeof AuthenticatedDossiersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dossiers/$id/': {
      id: '/_authenticated/dossiers/$id/'
      path: '/'
      fullPath: '/dossiers/$id/'
      preLoaderRoute: typeof AuthenticatedDossiersIdIndexRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/tiers-payeurs': {
      id: '/_authenticated/dossiers/$id/tiers-payeurs'
      path: '/tiers-payeurs'
      fullPath: '/dossiers/$id/tiers-payeurs'
      preLoaderRoute: typeof AuthenticatedDossiersIdTiersPayeursRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/synthese': {
      id: '/_authenticated/dossiers/$id/synthese'
      path: '/synthese'
      fullPath: '/dossiers/$id/synthese'
      preLoaderRoute: typeof AuthenticatedDossiersIdSyntheseRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/survie-proches': {
      id: '/_authenticated/dossiers/$id/survie-proches'
      path: '/survie-proches'
      fullPath: '/dossiers/$id/survie-proches'
      preLoaderRoute: typeof AuthenticatedDossiersIdSurvieProchesRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/patrimoniaux-temporaires': {
      id: '/_authenticated/dossiers/$id/patrimoniaux-temporaires'
      path: '/patrimoniaux-temporaires'
      fullPath: '/dossiers/$id/patrimoniaux-temporaires'
      preLoaderRoute: typeof AuthenticatedDossiersIdPatrimoniauxTemporairesRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/patrimoniaux-permanents': {
      id: '/_authenticated/dossiers/$id/patrimoniaux-permanents'
      path: '/patrimoniaux-permanents'
      fullPath: '/dossiers/$id/patrimoniaux-permanents'
      preLoaderRoute: typeof AuthenticatedDossiersIdPatrimoniauxPermanentsRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/interets': {
      id: '/_authenticated/dossiers/$id/interets'
      path: '/interets'
      fullPath: '/dossiers/$id/interets'
      preLoaderRoute: typeof AuthenticatedDossiersIdInteretsRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/extrapatrimoniaux-temporaires': {
      id: '/_authenticated/dossiers/$id/extrapatrimoniaux-temporaires'
      path: '/extrapatrimoniaux-temporaires'
      fullPath: '/dossiers/$id/extrapatrimoniaux-temporaires'
      preLoaderRoute: typeof AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/extrapatrimoniaux-permanents': {
      id: '/_authenticated/dossiers/$id/extrapatrimoniaux-permanents'
      path: '/extrapatrimoniaux-permanents'
      fullPath: '/dossiers/$id/extrapatrimoniaux-permanents'
      preLoaderRoute: typeof AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/deces': {
      id: '/_authenticated/dossiers/$id/deces'
      path: '/deces'
      fullPath: '/dossiers/$id/deces'
      preLoaderRoute: typeof AuthenticatedDossiersIdDecesRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/comparateur': {
      id: '/_authenticated/dossiers/$id/comparateur'
      path: '/comparateur'
      fullPath: '/dossiers/$id/comparateur'
      preLoaderRoute: typeof AuthenticatedDossiersIdComparateurRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/dossiers/$id/activite': {
      id: '/_authenticated/dossiers/$id/activite'
      path: '/activite'
      fullPath: '/dossiers/$id/activite'
      preLoaderRoute: typeof AuthenticatedDossiersIdActiviteRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
    '/_authenticated/referentiels/$code/editions/$editionId': {
      id: '/_authenticated/referentiels/$code/editions/$editionId'
      path: '/editions/$editionId'
      fullPath: '/referentiels/$code/editions/$editionId'
      preLoaderRoute: typeof AuthenticatedReferentielsCodeEditionsEditionIdRouteImport
      parentRoute: typeof AuthenticatedReferentielsCodeRoute
    }
    '/_authenticated/dossiers/$id/snapshots/$snapshotId': {
      id: '/_authenticated/dossiers/$id/snapshots/$snapshotId'
      path: '/snapshots/$snapshotId'
      fullPath: '/dossiers/$id/snapshots/$snapshotId'
      preLoaderRoute: typeof AuthenticatedDossiersIdSnapshotsSnapshotIdRouteImport
      parentRoute: typeof AuthenticatedDossiersIdRoute
    }
  }
}

interface AuthenticatedReferentielsCodeRouteChildren {
  AuthenticatedReferentielsCodeEditionsEditionIdRoute: typeof AuthenticatedReferentielsCodeEditionsEditionIdRoute
}

const AuthenticatedReferentielsCodeRouteChildren: AuthenticatedReferentielsCodeRouteChildren =
  {
    AuthenticatedReferentielsCodeEditionsEditionIdRoute:
      AuthenticatedReferentielsCodeEditionsEditionIdRoute,
  }

const AuthenticatedReferentielsCodeRouteWithChildren =
  AuthenticatedReferentielsCodeRoute._addFileChildren(
    AuthenticatedReferentielsCodeRouteChildren,
  )

interface AuthenticatedReferentielsRouteChildren {
  AuthenticatedReferentielsCodeRoute: typeof AuthenticatedReferentielsCodeRouteWithChildren
  AuthenticatedReferentielsIndexRoute: typeof AuthenticatedReferentielsIndexRoute
}

const AuthenticatedReferentielsRouteChildren: AuthenticatedReferentielsRouteChildren =
  {
    AuthenticatedReferentielsCodeRoute:
      AuthenticatedReferentielsCodeRouteWithChildren,
    AuthenticatedReferentielsIndexRoute: AuthenticatedReferentielsIndexRoute,
  }

const AuthenticatedReferentielsRouteWithChildren =
  AuthenticatedReferentielsRoute._addFileChildren(
    AuthenticatedReferentielsRouteChildren,
  )

interface AuthenticatedDossiersIdRouteChildren {
  AuthenticatedDossiersIdActiviteRoute: typeof AuthenticatedDossiersIdActiviteRoute
  AuthenticatedDossiersIdComparateurRoute: typeof AuthenticatedDossiersIdComparateurRoute
  AuthenticatedDossiersIdDecesRoute: typeof AuthenticatedDossiersIdDecesRoute
  AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRoute: typeof AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRoute
  AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRoute: typeof AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRoute
  AuthenticatedDossiersIdInteretsRoute: typeof AuthenticatedDossiersIdInteretsRoute
  AuthenticatedDossiersIdPatrimoniauxPermanentsRoute: typeof AuthenticatedDossiersIdPatrimoniauxPermanentsRoute
  AuthenticatedDossiersIdPatrimoniauxTemporairesRoute: typeof AuthenticatedDossiersIdPatrimoniauxTemporairesRoute
  AuthenticatedDossiersIdSurvieProchesRoute: typeof AuthenticatedDossiersIdSurvieProchesRoute
  AuthenticatedDossiersIdSyntheseRoute: typeof AuthenticatedDossiersIdSyntheseRoute
  AuthenticatedDossiersIdTiersPayeursRoute: typeof AuthenticatedDossiersIdTiersPayeursRoute
  AuthenticatedDossiersIdIndexRoute: typeof AuthenticatedDossiersIdIndexRoute
  AuthenticatedDossiersIdSnapshotsSnapshotIdRoute: typeof AuthenticatedDossiersIdSnapshotsSnapshotIdRoute
}

const AuthenticatedDossiersIdRouteChildren: AuthenticatedDossiersIdRouteChildren =
  {
    AuthenticatedDossiersIdActiviteRoute: AuthenticatedDossiersIdActiviteRoute,
    AuthenticatedDossiersIdComparateurRoute:
      AuthenticatedDossiersIdComparateurRoute,
    AuthenticatedDossiersIdDecesRoute: AuthenticatedDossiersIdDecesRoute,
    AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRoute:
      AuthenticatedDossiersIdExtrapatrimoniauxPermanentsRoute,
    AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRoute:
      AuthenticatedDossiersIdExtrapatrimoniauxTemporairesRoute,
    AuthenticatedDossiersIdInteretsRoute: AuthenticatedDossiersIdInteretsRoute,
    AuthenticatedDossiersIdPatrimoniauxPermanentsRoute:
      AuthenticatedDossiersIdPatrimoniauxPermanentsRoute,
    AuthenticatedDossiersIdPatrimoniauxTemporairesRoute:
      AuthenticatedDossiersIdPatrimoniauxTemporairesRoute,
    AuthenticatedDossiersIdSurvieProchesRoute:
      AuthenticatedDossiersIdSurvieProchesRoute,
    AuthenticatedDossiersIdSyntheseRoute: AuthenticatedDossiersIdSyntheseRoute,
    AuthenticatedDossiersIdTiersPayeursRoute:
      AuthenticatedDossiersIdTiersPayeursRoute,
    AuthenticatedDossiersIdIndexRoute: AuthenticatedDossiersIdIndexRoute,
    AuthenticatedDossiersIdSnapshotsSnapshotIdRoute:
      AuthenticatedDossiersIdSnapshotsSnapshotIdRoute,
  }

const AuthenticatedDossiersIdRouteWithChildren =
  AuthenticatedDossiersIdRoute._addFileChildren(
    AuthenticatedDossiersIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCabinetRoute: typeof AuthenticatedCabinetRoute
  AuthenticatedReferentielsRoute: typeof AuthenticatedReferentielsRouteWithChildren
  AuthenticatedTauxLegalRoute: typeof AuthenticatedTauxLegalRoute
  AuthenticatedDossiersIdRoute: typeof AuthenticatedDossiersIdRouteWithChildren
  AuthenticatedDossiersIndexRoute: typeof AuthenticatedDossiersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCabinetRoute: AuthenticatedCabinetRoute,
  AuthenticatedReferentielsRoute: AuthenticatedReferentielsRouteWithChildren,
  AuthenticatedTauxLegalRoute: AuthenticatedTauxLegalRoute,
  AuthenticatedDossiersIdRoute: AuthenticatedDossiersIdRouteWithChildren,
  AuthenticatedDossiersIndexRoute: AuthenticatedDossiersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
